steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['install', '-g', 'firebase-tools',]
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['use', 'sbcs-virtual-prod']
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['--prefix', './functions', 'install']
  # Build
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['rebuild', 'node-sass']
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['run', 'build:prod',]
  # Deploy
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['run', 'deploy',]